export const LEVELS = [
  {
    id: 1,
    name: "Level 1",
    boardId: "branchingIntro",
    difficultyLabel: "Warm Up",
    tutorialText: "A gentle start, but you still need to reset the route for the next train.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "left",
    },
    trainSpeed: 92,
    trains: [
      { id: "l1-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l1-t2", color: "red", spawnPointId: "mainSpawn", spawnTime: 3.8 },
    ],
  },
  {
    id: 2,
    name: "Level 2",
    boardId: "branchingIntro",
    difficultyLabel: "Getting Ready",
    tutorialText: "A few more trains, with less time to leave the route in the wrong place.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "left",
    },
    trainSpeed: 95,
    trains: [
      { id: "l2-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l2-t2", color: "red", spawnPointId: "mainSpawn", spawnTime: 3.2 },
      { id: "l2-t3", color: "green", spawnPointId: "mainSpawn", spawnTime: 6.1 },
    ],
  },
  {
    id: 3,
    name: "Level 3",
    boardId: "branchingIntro",
    difficultyLabel: "Steady Traffic",
    tutorialText: "Now the route changes come often enough that you need to plan the next train early.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "left",
    },
    trainSpeed: 98,
    trains: [
      { id: "l3-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l3-t2", color: "gray", spawnPointId: "mainSpawn", spawnTime: 2.8 },
      { id: "l3-t3", color: "red", spawnPointId: "mainSpawn", spawnTime: 5.3 },
      { id: "l3-t4", color: "green", spawnPointId: "mainSpawn", spawnTime: 7.7 },
    ],
  },
  {
    id: 4,
    name: "Level 4",
    boardId: "branchingIntro",
    difficultyLabel: "Bigger Queue",
    tutorialText: "The pace is more demanding now. Reset quickly after each train commits.",
    initialSwitchStates: {
      s1: "left",
      s2: "right",
      s3: "left",
    },
    trainSpeed: 101,
    trains: [
      { id: "l4-t1", color: "gray", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l4-t2", color: "blue", spawnPointId: "mainSpawn", spawnTime: 2.6 },
      { id: "l4-t3", color: "green", spawnPointId: "mainSpawn", spawnTime: 5.0 },
      { id: "l4-t4", color: "red", spawnPointId: "mainSpawn", spawnTime: 7.3 },
      { id: "l4-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 9.5 },
    ],
  },
  {
    id: 5,
    name: "Level 5",
    boardId: "branchingIntro",
    difficultyLabel: "First Push",
    tutorialText: "This is the first real challenge. Stay ahead of the route and keep resetting early.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "right",
    },
    trainSpeed: 105,
    trains: [
      { id: "l5-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l5-t2", color: "gray", spawnPointId: "mainSpawn", spawnTime: 2.2 },
      { id: "l5-t3", color: "red", spawnPointId: "mainSpawn", spawnTime: 4.3 },
      { id: "l5-t4", color: "green", spawnPointId: "mainSpawn", spawnTime: 6.3 },
      { id: "l5-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 8.2 },
      { id: "l5-t6", color: "red", spawnPointId: "mainSpawn", spawnTime: 10.0 },
    ],
  },
  {
    id: 6,
    name: "Level 6",
    boardId: "branchingIntro",
    difficultyLabel: "Route Reset",
    tutorialText: "A step up from Level 5. Reset the route quickly after each train.",
    initialSwitchStates: {
      s1: "right",
      s2: "left",
      s3: "left",
    },
    trainSpeed: 104,
    trains: [
      { id: "l6-t1", color: "red", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l6-t2", color: "gray", spawnPointId: "mainSpawn", spawnTime: 2.5 },
      { id: "l6-t3", color: "blue", spawnPointId: "mainSpawn", spawnTime: 5.0 },
      { id: "l6-t4", color: "green", spawnPointId: "mainSpawn", spawnTime: 7.4 },
      { id: "l6-t5", color: "red", spawnPointId: "mainSpawn", spawnTime: 9.7 },
      { id: "l6-t6", color: "gray", spawnPointId: "mainSpawn", spawnTime: 11.9 },
    ],
  },
  {
    id: 7,
    name: "Level 7",
    boardId: "branchingIntro",
    difficultyLabel: "Upper Pressure",
    tutorialText: "The top half changes often now. Do not leave the second switch behind.",
    initialSwitchStates: {
      s1: "left",
      s2: "right",
      s3: "right",
    },
    trainSpeed: 107,
    trains: [
      { id: "l7-t1", color: "gray", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l7-t2", color: "blue", spawnPointId: "mainSpawn", spawnTime: 2.3 },
      { id: "l7-t3", color: "green", spawnPointId: "mainSpawn", spawnTime: 4.5 },
      { id: "l7-t4", color: "red", spawnPointId: "mainSpawn", spawnTime: 6.6 },
      { id: "l7-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 8.7 },
      { id: "l7-t6", color: "green", spawnPointId: "mainSpawn", spawnTime: 10.7 },
    ],
  },
  {
    id: 8,
    name: "Level 8",
    boardId: "branchingIntro",
    difficultyLabel: "Full Mix",
    tutorialText: "All four destinations matter. Read the whole route tree before each split.",
    initialSwitchStates: {
      s1: "right",
      s2: "left",
      s3: "right",
    },
    trainSpeed: 110,
    trains: [
      { id: "l8-t1", color: "green", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l8-t2", color: "blue", spawnPointId: "mainSpawn", spawnTime: 2.1 },
      { id: "l8-t3", color: "red", spawnPointId: "mainSpawn", spawnTime: 4.1 },
      { id: "l8-t4", color: "gray", spawnPointId: "mainSpawn", spawnTime: 6.0 },
      { id: "l8-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 7.8 },
      { id: "l8-t6", color: "green", spawnPointId: "mainSpawn", spawnTime: 9.5 },
      { id: "l8-t7", color: "red", spawnPointId: "mainSpawn", spawnTime: 11.2 },
    ],
  },
  {
    id: 9,
    name: "Level 9",
    boardId: "branchingIntro",
    difficultyLabel: "Reset Pressure",
    tutorialText: "The routes change fast now. Recover immediately after each train commits.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "right",
    },
    trainSpeed: 113,
    trains: [
      { id: "l9-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l9-t2", color: "red", spawnPointId: "mainSpawn", spawnTime: 2.0 },
      { id: "l9-t3", color: "gray", spawnPointId: "mainSpawn", spawnTime: 3.9 },
      { id: "l9-t4", color: "green", spawnPointId: "mainSpawn", spawnTime: 5.7 },
      { id: "l9-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 7.4 },
      { id: "l9-t6", color: "gray", spawnPointId: "mainSpawn", spawnTime: 9.0 },
      { id: "l9-t7", color: "red", spawnPointId: "mainSpawn", spawnTime: 10.6 },
    ],
  },
  {
    id: 10,
    name: "Level 10",
    boardId: "branchingIntro",
    difficultyLabel: "Board Test",
    tutorialText: "A full-route test. Stay ahead of the network and keep every switch ready.",
    initialSwitchStates: {
      s1: "right",
      s2: "right",
      s3: "left",
    },
    trainSpeed: 116,
    trains: [
      { id: "l10-t1", color: "red", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l10-t2", color: "blue", spawnPointId: "mainSpawn", spawnTime: 1.9 },
      { id: "l10-t3", color: "green", spawnPointId: "mainSpawn", spawnTime: 3.7 },
      { id: "l10-t4", color: "gray", spawnPointId: "mainSpawn", spawnTime: 5.4 },
      { id: "l10-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 7.0 },
      { id: "l10-t6", color: "red", spawnPointId: "mainSpawn", spawnTime: 8.6 },
      { id: "l10-t7", color: "gray", spawnPointId: "mainSpawn", spawnTime: 10.1 },
      { id: "l10-t8", color: "green", spawnPointId: "mainSpawn", spawnTime: 11.6 },
    ],
  },
  {
    id: 11,
    name: "Level 11",
    boardId: "branchingIntro",
    difficultyLabel: "New Destination",
    tutorialText: "Yellow is new, but the pace does not slow down. Read all the way through Switch 4.",
    initialSwitchStates: {
      s1: "left",
      s2: "right",
      s3: "left",
      s4: "right",
    },
    trainSpeed: 118,
    trains: [
      { id: "l11-t1", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l11-t2", color: "blue", spawnPointId: "mainSpawn", spawnTime: 2.7 },
      { id: "l11-t3", color: "gray", spawnPointId: "mainSpawn", spawnTime: 5.2 },
      { id: "l11-t4", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 7.6 },
      { id: "l11-t5", color: "red", spawnPointId: "mainSpawn", spawnTime: 10.0 },
    ],
  },
  {
    id: 12,
    name: "Level 12",
    boardId: "branchingIntro",
    difficultyLabel: "One More Split",
    tutorialText: "Gray and yellow share the same first path, so you need to finish the route, not guess it.",
    initialSwitchStates: {
      s1: "left",
      s2: "right",
      s3: "right",
      s4: "left",
    },
    trainSpeed: 120,
    trains: [
      { id: "l12-t1", color: "gray", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l12-t2", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 2.5 },
      { id: "l12-t3", color: "gray", spawnPointId: "mainSpawn", spawnTime: 4.9 },
      { id: "l12-t4", color: "red", spawnPointId: "mainSpawn", spawnTime: 7.2 },
      { id: "l12-t5", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 9.4 },
      { id: "l12-t6", color: "blue", spawnPointId: "mainSpawn", spawnTime: 11.5 },
    ],
  },
  {
    id: 13,
    name: "Level 13",
    boardId: "branchingIntro",
    difficultyLabel: "Mixed Depth",
    tutorialText: "Now the route keeps jumping between the lower half and the deeper yellow branch.",
    initialSwitchStates: {
      s1: "right",
      s2: "right",
      s3: "left",
      s4: "right",
    },
    trainSpeed: 122,
    trains: [
      { id: "l13-t1", color: "red", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l13-t2", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 2.3 },
      { id: "l13-t3", color: "green", spawnPointId: "mainSpawn", spawnTime: 4.5 },
      { id: "l13-t4", color: "gray", spawnPointId: "mainSpawn", spawnTime: 6.6 },
      { id: "l13-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 8.6 },
      { id: "l13-t6", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 10.5 },
      { id: "l13-t7", color: "red", spawnPointId: "mainSpawn", spawnTime: 12.3 },
    ],
  },
  {
    id: 14,
    name: "Level 14",
    boardId: "branchingIntro",
    difficultyLabel: "Upper Route Pressure",
    tutorialText: "The upper routes are busy now. Switch 2 and Switch 4 both need fast resets.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "right",
      s4: "left",
    },
    trainSpeed: 125,
    trains: [
      { id: "l14-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l14-t2", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 2.1 },
      { id: "l14-t3", color: "gray", spawnPointId: "mainSpawn", spawnTime: 4.1 },
      { id: "l14-t4", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 6.0 },
      { id: "l14-t5", color: "red", spawnPointId: "mainSpawn", spawnTime: 7.8 },
      { id: "l14-t6", color: "green", spawnPointId: "mainSpawn", spawnTime: 9.5 },
      { id: "l14-t7", color: "gray", spawnPointId: "mainSpawn", spawnTime: 11.1 },
      { id: "l14-t8", color: "blue", spawnPointId: "mainSpawn", spawnTime: 12.7 },
    ],
  },
  {
    id: 15,
    name: "Level 15",
    boardId: "branchingIntro",
    difficultyLabel: "Five-House Test",
    tutorialText: "Full board test. Keep all four switches ready and recover immediately after each commit.",
    initialSwitchStates: {
      s1: "right",
      s2: "right",
      s3: "left",
      s4: "right",
    },
    trainSpeed: 128,
    trains: [
      { id: "l15-t1", color: "red", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l15-t2", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 2.0 },
      { id: "l15-t3", color: "blue", spawnPointId: "mainSpawn", spawnTime: 3.9 },
      { id: "l15-t4", color: "gray", spawnPointId: "mainSpawn", spawnTime: 5.7 },
      { id: "l15-t5", color: "green", spawnPointId: "mainSpawn", spawnTime: 7.4 },
      { id: "l15-t6", color: "yellow", spawnPointId: "mainSpawn", spawnTime: 9.0 },
      { id: "l15-t7", color: "blue", spawnPointId: "mainSpawn", spawnTime: 10.5 },
      { id: "l15-t8", color: "red", spawnPointId: "mainSpawn", spawnTime: 11.9 },
      { id: "l15-t9", color: "gray", spawnPointId: "mainSpawn", spawnTime: 13.3 },
    ],
  },
];