export const LEVELS = [
  {
    id: 1,
    name: "Level 1",
    boardId: "branchingIntro",
    difficultyLabel: "Warm Up",
    tutorialText: "A slow start. Follow the route and send each train to the correct house.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "left",
    },
    trainSpeed: 88,
    trains: [
      { id: "l1-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l1-t2", color: "red", spawnPointId: "mainSpawn", spawnTime: 4.5 },
    ],
  },
  {
    id: 2,
    name: "Level 2",
    boardId: "branchingIntro",
    difficultyLabel: "Getting Ready",
    tutorialText: "A few more trains, but still enough time to reset the route.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "left",
    },
    trainSpeed: 89,
    trains: [
      { id: "l2-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l2-t2", color: "red", spawnPointId: "mainSpawn", spawnTime: 4.2 },
      { id: "l2-t3", color: "green", spawnPointId: "mainSpawn", spawnTime: 8.2 },
    ],
  },
  {
    id: 3,
    name: "Level 3",
    boardId: "branchingIntro",
    difficultyLabel: "Steady Traffic",
    tutorialText: "Now there are four trains. Stay ahead of the next split.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "left",
    },
    trainSpeed: 91,
    trains: [
      { id: "l3-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l3-t2", color: "gray", spawnPointId: "mainSpawn", spawnTime: 3.5 },
      { id: "l3-t3", color: "red", spawnPointId: "mainSpawn", spawnTime: 6.8 },
      { id: "l3-t4", color: "green", spawnPointId: "mainSpawn", spawnTime: 10.0 },
    ],
  },
  {
    id: 4,
    name: "Level 4",
    boardId: "branchingIntro",
    difficultyLabel: "Bigger Queue",
    tutorialText: "More trains are coming now, but the pace is still manageable.",
    initialSwitchStates: {
      s1: "left",
      s2: "right",
      s3: "left",
    },
    trainSpeed: 94,
    trains: [
      { id: "l4-t1", color: "gray", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l4-t2", color: "blue", spawnPointId: "mainSpawn", spawnTime: 3.0 },
      { id: "l4-t3", color: "green", spawnPointId: "mainSpawn", spawnTime: 5.9 },
      { id: "l4-t4", color: "red", spawnPointId: "mainSpawn", spawnTime: 8.7 },
      { id: "l4-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 11.3 },
    ],
  },
  {
    id: 5,
    name: "Level 5",
    boardId: "branchingIntro",
    difficultyLabel: "First Push",
    tutorialText: "This is the first real challenge. Keep resetting the route before the next arrival.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "right",
    },
    trainSpeed: 100,
    trains: [
      { id: "l5-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l5-t2", color: "gray", spawnPointId: "mainSpawn", spawnTime: 2.4 },
      { id: "l5-t3", color: "red", spawnPointId: "mainSpawn", spawnTime: 4.8 },
      { id: "l5-t4", color: "green", spawnPointId: "mainSpawn", spawnTime: 7.0 },
      { id: "l5-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 9.1 },
      { id: "l5-t6", color: "red", spawnPointId: "mainSpawn", spawnTime: 11.1 },
      { id: "l5-t7", color: "gray", spawnPointId: "mainSpawn", spawnTime: 13.0 },
    ],
  },
  {
    id: 6,
    name: "Level 6",
    boardId: "branchingIntro",
    difficultyLabel: "Route Reset",
    tutorialText: "A step up from Level 5. Reset the route quickly after each train.",
    initialSwitchStates: {
      s1: "right",
      s2: "left",
      s3: "left",
    },
    trainSpeed: 104,
    trains: [
      { id: "l6-t1", color: "red", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l6-t2", color: "gray", spawnPointId: "mainSpawn", spawnTime: 2.5 },
      { id: "l6-t3", color: "blue", spawnPointId: "mainSpawn", spawnTime: 5.0 },
      { id: "l6-t4", color: "green", spawnPointId: "mainSpawn", spawnTime: 7.4 },
      { id: "l6-t5", color: "red", spawnPointId: "mainSpawn", spawnTime: 9.7 },
      { id: "l6-t6", color: "gray", spawnPointId: "mainSpawn", spawnTime: 11.9 },
    ],
  },
  {
    id: 7,
    name: "Level 7",
    boardId: "branchingIntro",
    difficultyLabel: "Upper Pressure",
    tutorialText: "The top half changes often now. Do not leave the second switch behind.",
    initialSwitchStates: {
      s1: "left",
      s2: "right",
      s3: "right",
    },
    trainSpeed: 107,
    trains: [
      { id: "l7-t1", color: "gray", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l7-t2", color: "blue", spawnPointId: "mainSpawn", spawnTime: 2.3 },
      { id: "l7-t3", color: "green", spawnPointId: "mainSpawn", spawnTime: 4.5 },
      { id: "l7-t4", color: "red", spawnPointId: "mainSpawn", spawnTime: 6.6 },
      { id: "l7-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 8.7 },
      { id: "l7-t6", color: "green", spawnPointId: "mainSpawn", spawnTime: 10.7 },
    ],
  },
  {
    id: 8,
    name: "Level 8",
    boardId: "branchingIntro",
    difficultyLabel: "Full Mix",
    tutorialText: "All four destinations matter. Read the whole route tree before each split.",
    initialSwitchStates: {
      s1: "right",
      s2: "left",
      s3: "right",
    },
    trainSpeed: 110,
    trains: [
      { id: "l8-t1", color: "green", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l8-t2", color: "blue", spawnPointId: "mainSpawn", spawnTime: 2.1 },
      { id: "l8-t3", color: "red", spawnPointId: "mainSpawn", spawnTime: 4.1 },
      { id: "l8-t4", color: "gray", spawnPointId: "mainSpawn", spawnTime: 6.0 },
      { id: "l8-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 7.8 },
      { id: "l8-t6", color: "green", spawnPointId: "mainSpawn", spawnTime: 9.5 },
      { id: "l8-t7", color: "red", spawnPointId: "mainSpawn", spawnTime: 11.2 },
    ],
  },
  {
    id: 9,
    name: "Level 9",
    boardId: "branchingIntro",
    difficultyLabel: "Reset Pressure",
    tutorialText: "The routes change fast now. Recover immediately after each train commits.",
    initialSwitchStates: {
      s1: "left",
      s2: "left",
      s3: "right",
    },
    trainSpeed: 113,
    trains: [
      { id: "l9-t1", color: "blue", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l9-t2", color: "red", spawnPointId: "mainSpawn", spawnTime: 2.0 },
      { id: "l9-t3", color: "gray", spawnPointId: "mainSpawn", spawnTime: 3.9 },
      { id: "l9-t4", color: "green", spawnPointId: "mainSpawn", spawnTime: 5.7 },
      { id: "l9-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 7.4 },
      { id: "l9-t6", color: "gray", spawnPointId: "mainSpawn", spawnTime: 9.0 },
      { id: "l9-t7", color: "red", spawnPointId: "mainSpawn", spawnTime: 10.6 },
    ],
  },
  {
    id: 10,
    name: "Level 10",
    boardId: "branchingIntro",
    difficultyLabel: "Board Test",
    tutorialText: "A full-route test. Stay ahead of the network and keep every switch ready.",
    initialSwitchStates: {
      s1: "right",
      s2: "right",
      s3: "left",
    },
    trainSpeed: 116,
    trains: [
      { id: "l10-t1", color: "red", spawnPointId: "mainSpawn", spawnTime: 0.0 },
      { id: "l10-t2", color: "blue", spawnPointId: "mainSpawn", spawnTime: 1.9 },
      { id: "l10-t3", color: "green", spawnPointId: "mainSpawn", spawnTime: 3.7 },
      { id: "l10-t4", color: "gray", spawnPointId: "mainSpawn", spawnTime: 5.4 },
      { id: "l10-t5", color: "blue", spawnPointId: "mainSpawn", spawnTime: 7.0 },
      { id: "l10-t6", color: "red", spawnPointId: "mainSpawn", spawnTime: 8.6 },
      { id: "l10-t7", color: "gray", spawnPointId: "mainSpawn", spawnTime: 10.1 },
      { id: "l10-t8", color: "green", spawnPointId: "mainSpawn", spawnTime: 11.6 },
    ],
  },
];